version: "3.3"

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Host:Container   
    expose:   # expose only inside the Docker network
      - "8000"
    environment:
      - FMP_API_KEY=${FMP_API_KEY:-demo}
      - TRANSPORT=${TRANSPORT:-sse}
    volumes:
      - ./src:/app/src
    restart: unless-stopped
    command: python -m src.server --streamable --port 8000 --host 0.0.0.0
